/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Task {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : Time,
  'description' : string,
  'priority' : Priority,
}
export interface TaskInput {
  'id' : [] | [bigint],
  'title' : string,
  'description' : string,
  'priority' : Priority,
}
export type Time = bigint;
export interface _SERVICE {
  'createTask' : ActorMethod<[TaskInput], bigint>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[bigint], Task>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'updateTask' : ActorMethod<[TaskInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];