/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'priority' : Priority,
});
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'createdAt' : Time,
  'description' : IDL.Text,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func([TaskInput], [IDL.Nat], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'updateTask' : IDL.Func([TaskInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'createdAt' : Time,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func([TaskInput], [IDL.Nat], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'updateTask' : IDL.Func([TaskInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };